spring:
  application:
    name: speedy.io

server:
  port: 8081

logging:
  level:
    org:
      srpingframework:
        security: DEBUG

api:
  speedy:
    base_url: https://reporting.rpdpymnt.com
    base_version: /api/v3
    api_key: not received
    login:
      path: /merchant/user/login
    transactions_report:
      path: /transactions/report
    transaction_list:
      path: /transaction/list
    transaction:
      path: /transaction
    client:
      path: /client