spring:
  application:
    name: speedy.io

server:
  port: 8081

logging:
  level:
    org:
      srpingframework:
        security: DEBUG

api:
  speedy:
    base_url: http://localhost:8089
    base_version: /api/v3
    api_key: not-received
    login:
      path: /merchant/user/login
    transactions_report:
      path: /transactions/report
    transaction_list:
      path: /list
    transaction:
      path: /transaction
    client:
      path: /client

  mock:
    email: demo@financialhouse.io
    password: cjaiU8CV